// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get_my_profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function db(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my doctor profile",
  description: "Return the signed-in doctor's Doctylia profile (name, specialization, slug, plan, contact details).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await db(ctx).from("profiles").select("*").eq("id", ctx.getUserId()).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: "No profile found for this user." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list_appointments.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function db2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_appointments_default = defineTool2({
  name: "list_appointments",
  title: "List appointments",
  description: "List the signed-in doctor's appointments. Optionally filter by status, a date range, or limit the result count.",
  inputSchema: {
    status: z.enum(["pending", "confirmed", "completed", "cancelled", "no_show"]).optional().describe("Filter by appointment status."),
    from_date: z.string().optional().describe("Start date (YYYY-MM-DD), inclusive."),
    to_date: z.string().optional().describe("End date (YYYY-MM-DD), inclusive."),
    limit: z.number().int().positive().max(200).optional().describe("Max rows to return. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, from_date, to_date, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = db2(ctx).from("appointments").select("id, patient_name, patient_phone, service_name, appointment_type, date, time_slot, status, token_number, amount, meeting_link, chief_complaint, created_at").eq("doctor_id", ctx.getUserId()).order("date", { ascending: false }).order("time_slot", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (from_date) q = q.gte("date", from_date);
    if (to_date) q = q.lte("date", to_date);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_patients.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function db3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_patients_default = defineTool3({
  name: "list_patients",
  title: "List patients",
  description: "List patients belonging to the signed-in doctor. Optional text search by name or phone.",
  inputSchema: {
    search: z2.string().trim().optional().describe("Substring match against patient name or phone."),
    limit: z2.number().int().positive().max(200).optional().describe("Max rows. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = db3(ctx).from("patients").select("*").eq("doctor_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (search) q = q.or(`name.ilike.%${search}%,phone.ilike.%${search}%`);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, patients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_dashboard_stats.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
function db4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_dashboard_stats_default = defineTool4({
  name: "get_dashboard_stats",
  title: "Get dashboard stats",
  description: "Return quick counts for the signed-in doctor: total patients, total appointments, today's appointments, and pending appointments.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = db4(ctx);
    const uid = ctx.getUserId();
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const [patients, appts, todayAppts, pending] = await Promise.all([
      client.from("patients").select("id", { count: "exact", head: true }).eq("doctor_id", uid),
      client.from("appointments").select("id", { count: "exact", head: true }).eq("doctor_id", uid),
      client.from("appointments").select("id", { count: "exact", head: true }).eq("doctor_id", uid).eq("date", today),
      client.from("appointments").select("id", { count: "exact", head: true }).eq("doctor_id", uid).eq("status", "pending")
    ]);
    const stats = {
      total_patients: patients.count ?? 0,
      total_appointments: appts.count ?? 0,
      appointments_today: todayAppts.count ?? 0,
      pending_appointments: pending.count ?? 0,
      date: today
    };
    return {
      content: [{ type: "text", text: JSON.stringify(stats, null, 2) }],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/tools/list_reviews.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function db5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_reviews_default = defineTool5({
  name: "list_reviews",
  title: "List patient reviews",
  description: "List patient reviews for the signed-in doctor. Optionally filter by minimum star rating.",
  inputSchema: {
    min_rating: z3.number().int().min(1).max(5).optional().describe("Only return reviews with rating >= this value."),
    limit: z3.number().int().positive().max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ min_rating, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = db5(ctx).from("reviews").select("*").eq("doctor_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (min_rating) q = q.gte("rating", min_rating);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, reviews: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "abxvamwcjiqpahfipwqp";
var mcp_default = defineMcp({
  name: "doctylia-mcp",
  title: "Doctylia",
  version: "0.1.0",
  instructions: "Doctylia MCP server for signed-in doctors. Read your profile, appointments, patients, reviews, and dashboard stats. All tools act as the authenticated doctor and respect row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, get_dashboard_stats_default, list_appointments_default, list_patients_default, list_reviews_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
